---
title: "Chapter 2"
author: "Yifei Liu"
date: "2/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 2.1 Vectors

```{r}

a <- 1:3
b <- 4:5
c <- matrix(c(3,2,1), 3,1, byrow = T)
d <- matrix(c(6,5,4), nrow = 3, byrow = T)

c
d

```

## 2.2 Matrices



## 2.3 Matrix Arithmetic

```{r}
a <- matrix(1:4, ncol = 2, byrow = T)
b <- matrix(5:8, ncol = 2, byrow = T)

a %*% b

b %*% a

a <- matrix(c(1,1,2,2,1,3,3,1,4,4,1,5), byrow = T, ncol = 3)
b <- matrix(rep(0, 4), ncol = 1)
solve(a, b)
```

```{r}
u <- matrix(1:4, ncol = 2, byrow = T)
v <- matrix(5:8, ncol = 2, byrow = T)
w <- matrix(c(2,2,3,5), ncol = 2, byrow = T)

a <- matrix(1:6, ncol = 3, byrow = T)
b <- matrix(1:6, ncol = 2, byrow = T)

u + v
2 * u



```

## 2.5 Special Matrics

### 2.5.1 Symmetrics and skew-symmetric matrices

A square $n \times n$ matrix $A = (a_{ij})$ is *symmetric* if $\acute{A} = A$, i.e., $a_{ij} = a_{ij}$ for all i,j. 

A square matrix $B = (b_{ij})$ is *Skew-symmetric* if $\acute{B} = -B$ i.e. $b_{ij} = - b{ji}$ for all i, j. 


```{r}
# Example 2.5
A <- matrix(1:9, 3,3, byrow = T)
E <- matrix(c(1,0,0,0,1,0), 2,3, byrow = T)
F <- matrix(c(1,0,0,1,0,0), 3,2, byrow = T)

E %*% A
A %*% F
E %*% A %*% F

```

## 2.6 Partitioned Matrices

### 2.6.3 Implementation of partitioned matrices in R

```{r}
A <- matrix(1:6, 2,3)
B <- matrix(1:6, 2,3, byrow = T)

U <- cbind(A, B)
U[1:2, 3:6]

```




## 2.8 Matrixs

```{r}
a <- matrix(1:6, nrow = 2)
b <- matrix(1:6, nrow = 2, byrow = T)

x <- matrix(1:16, byrow = F, ncol = 4)

```


## 2.11

```{r}
# corss products

A<-matrix(c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=T)
B<-matrix(c(1,2,3,4,5,6),nrow=3,ncol=2,byrow=T)

identical(crossprod(A),t(A) %*% A)
identical(tcrossprod(A), A %*% t(A))


D<-matrix(c(1,2,3,4,5,6), 2,3,byrow=T)

identical(crossprod(A, D), t(D) %*% A)

# Ambiguity of vectors
X<-matrix(c(1,2,3,4,5,6,7,8,9),3,3,byrow=T)
a <- 1:3
b <- 4:6

a %*% X
X %*% b

# Diagoal matrices
test <- diag(c(1:5))
test


# Trace


```



## 2.13 Exercises

```{r}
a <- matrix(1:3, ncol = 1)
b <- matrix(4:6, ncol = 1)
u <- matrix(3:1, ncol = 1)
v <- matrix(6:4, ncol = 1)
w <- matrix(7:9, nrow = 1)

a + b
v - b
t(w) + b
3*u
t(w) - a
a %*% t(b)
b %*% t(a)
```


```{r}
x <- matrix(c(2,2,-3), ncol = 1)
y <- matrix(c(1,-2, 1), ncol = 1)


```

```{r}
A <- matrix(1:6, nrow = 2, byrow = T)
B <- matrix(1:6, nrow = 3, byrow = T)
U <- matrix(1:4, nrow = 2, byrow = T)
V <- matrix(5:8, nrow = 2, byrow = T)
W <- matrix(c(2,2,3,5), nrow = 2, byrow = T)
Z <- matrix(c(3,2,3,6), nrow = 2, byrow = T)


A %*% B
V %*% diag(U)
diag(t(B) %*% t(A))
diag(diag(U %*% V))
diag((diag(U)))
diag(diag(V))

identical(U %*% V, V %*% U)
identical(U %*% Z, Z %*% U)
identical(W %*% Z, Z %*% W)
```

```{r}
t(Z) %*% U %*% Z

```

```{r}
test <- matrix(-1, ncol = 5, nrow = 5) 
diag(test) <- 4

result <- matrix(c(103, 28, 15, -40, -106), ncol = 1)

Matrix::solve(test, result)


```






