---
title: "Untitled"
author: "Yifei Liu"
date: "1/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lpSolve)
library(MASS)
library(quadprog)
library(readxl)
library(dplyr)
detach("package:dplyr", unload=TRUE)
library(dplyr)
library(tidyquant)
library(ggcorrplot)
library(e1071)
library(kernlab)
library(broom)
theme_set(theme_minimal())
library(PerformanceAnalytics)

```


```{r}
loca <- "/Users/yifeiliu/Documents/R/data/book_exercise/stock.xlsx"

stocks <- read_xlsx(loca)

stocks <- stocks %>%
  select(Index, MR, PR, BR)

stocks %>%
  select(-Index) %>%
  cor() %>%
  ggcorrplot()

stock_cor <- stocks %>%
  select(-Index) %>%
  cor()

ret <- colMeans(select(stocks, -Index))

stock_cor %*% ret

correlation <- matrix(c(1, .2, .3, .2, 2, .4, .3, .4, 1), byrow = T, ncol = 3)
rets <- matrix(c(.02, .03, .021), nrow = 1)

solve.QP(Dmat = diag(3), c(1, 1, 1), Amat = correlation, bvec = rets)

Dmat <- diag(3)
dvec <- c(.01, .02, .04)
Amat <- matrix(c(1, -2, 0.9, -2, 1.5, 0.8, 0.9, 0.8, 2), byrow = T, ncol = 3)
bvec = c(0.025)

solve.QP(Dmat, dvec, , bvec)

Amat

test <- data.frame(
  x = rnorm(100),
  y = rnorm(100),
  class = c(rep("HD", 50), rep("LO", 50)))

ggplot(test, aes(x, y, color = class)) +
  geom_point()

```











